services:
  server:
    container_name: Backend
    build:
      dockerfile: Dockerfile
      target: server-final
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
    depends_on:
      - db
    secrets:
      - Database
      - Jwt

  identity:
    container_name: Identity
    build:
      dockerfile: Dockerfile
      target: identity-final
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
    depends_on:
      - db
    secrets:
      - Database
      - Jwt
        
  client:
    container_name: Frontend
    build:
      context: .
      dockerfile: Dockerfile
      target: client-final
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - server
      - identity
  
  db:
    container_name: Database
    image: postgres:17.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shish_byzh
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "54322:5432"

volumes:
  pgdata:
    
secrets:
  Database:
    file: ./database_secret.txt
  Jwt:
    file: ./jwt_secret.txt